export interface BookmarkHtmlNode {
  id?: string
  title?: string
  url?: string
  dateAdded?: number
  dateGroupModified?: number
  children?: BookmarkHtmlNode[]
}

/** Netscape bookmark interchange format, understood by Chrome, Edge and Firefox. */
export function buildBookmarkHtmlExport(roots: readonly BookmarkHtmlNode[]): string {
  const lines = [
    '<!DOCTYPE NETSCAPE-Bookmark-file-1>',
    '<!-- Generated by Curator. Import this file using your browser bookmark manager. -->',
    '<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">',
    '<META HTTP-EQUIV="Content-Security-Policy" CONTENT="default-src \'none\'; base-uri \'none\'">',
    '<TITLE>Bookmarks</TITLE>',
    '<H1>Bookmarks</H1>',
    '<DL><p>'
  ]
  const pending: Array<{ node?: BookmarkHtmlNode; depth: number }> = []
  for (let index = roots.length - 1; index >= 0; index--) pending.push({ node: roots[index], depth: 1 })

  while (pending.length) {
    const { node, depth } = pending.pop()!
    const indent = '    '.repeat(Math.min(depth, 32))
    if (!node) {
      lines.push(`${indent}</DL><p>`)
      continue
    }
    const dates = dateAttribute('ADD_DATE', node.dateAdded)
    if (typeof node.url === 'string') {
      lines.push(`${indent}<DT><A HREF="${escapeHtml(node.url)}"${dates}>${escapeHtml(node.title)}</A>`)
      continue
    }
    // Chrome's synthetic root is not a user folder. Keep every real folder,
    // including empty folders, and retain sibling order and duplicate links.
    const root = node.id === '0'
    if (!root) {
      const toolbar = node.id === '1' ? ' PERSONAL_TOOLBAR_FOLDER="true"' : ''
      lines.push(`${indent}<DT><H3${dates}${dateAttribute('LAST_MODIFIED', node.dateGroupModified)}${toolbar}>${escapeHtml(node.title)}</H3>`)
      lines.push(`${indent}<DL><p>`)
      pending.push({ depth })
    }
    const children = node.children || []
    for (let index = children.length - 1; index >= 0; index--) {
      pending.push({ node: children[index], depth: root ? depth : depth + 1 })
    }
  }
  lines.push('</DL><p>', '')
  return lines.join('\n')
}

function escapeHtml(value: unknown): string {
  return String(value ?? '').replace(/[&<>"']/g, character => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  })[character]!)
}

function dateAttribute(name: string, value?: number): string {
  return Number.isFinite(value) && value! > 0 ? ` ${name}="${Math.floor(value! / 1000)}"` : ''
}
